CREATE TABLE USERS (ID INT IDENTITY, EMAIL VARCHAR(50), PASSWORD VARCHAR(120), USERNAME VARCHAR(20));
CREATE TABLE USER_ROLES (USER_ID INT, ROLE_ID INT);
CREATE TABLE ROLES (ID INT IDENTITY, NAME VARCHAR(20));
CREATE TABLE COMMENTS (ID INT IDENTITY, USERNAME VARCHAR(20), COMMENT VARCHAR(200), PARENT_ID INT, CREATED_TIME TIMESTAMP);